dist: xenial

language: python

cache: pip

python:
    - "3.8"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pipenv install --dev
    - pip install gspread
    - pip install pymongo
