language: python

python:
    - "3.8"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip install pipenv --upgrade-strategy=only-if-needed
    - pip install gspread
    - pip install pymongo
